export const strings = {
	/* Categories */
	official: "Official fish",
	technicallyofficial: "Technically official fish",
	semiofficial: "Semi-official fish",
	unofficial: "Unofficial fish",
	
	/* Types */
	mineral: "Minerals",
	mcitems: "Minecraft items",
	mcblocks: "Minecraft blocks",
	mcmobs: "Minecraft mobs",
	mcrandom: "Minecraft randomized ores",
	oc: "OC fish",
	misc: "Miscellaneous",
	crossover: "Fish from other franchises",
	
	/* Headings */
	fullName: "Name",
	category: "Category",
	type: "Type",
	bitmap: "Bitmap sprite",
	vector: "Vector sprite",
	creator: "Creator",
	textureCreator: "Bitmap creator",
	vectorTextureCreator: "Vector creator",
	realName: "Real name",
	role: "Role",
};
export const fishList = {
	copper: { realName: "Tickee", role: "Miscellaneous annoyances", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Copper Fish" },
	emerald: { realName: "Plagee", role: "Advertising", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Emerald Fish" },
	lapis: { realName: "Iragee", role: "Flame wars", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Lapis Fish" },
	redstone: { realName: "Cussee", role: "Community Guidelines / FaQ / ToS", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Redstone Fish" },
	quartz: { realName: "Bumpee, Jumpee, Stretchee, Bonkee, Clonkee", role: "Subject derailment", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Quartz Fish" },
	iron: { realName: "Ingo, Blawbo & Crumbo", role: "Topic bumping", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Iron Fish" },
	coal: { realName: "Brunee", role: "Topic closing/opening", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Coal Fish" },
	diamond: { realName: "Cubzia", role: "Topic subject offenses", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Diamond Fish" },
	golden: { realName: "Tailee", role: "Quote chains", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Golden Fish" },
	netherite: { realName: "Tengreyee", role: "Spamming", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Netherite Fish" },
	ancientdebris: { realName: "Tengree", role: "Necroposting", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Ancient Debris Fish" },
	amethyst: { realName: "Notiee", role: "Topic pinning", category: "official", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Amethyst Fish" },
	
	
	ironnugget: { realName: "Thunkee", role: "Rapid bumping/bopping", category: "technicallyofficial", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Iron Nugget Fish" },
	goldnugget: { realName: "Bunkee", role: "False quoting", category: "technicallyofficial", type: "mineral", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", fullName: "Gold Nugget Fish" },
	ironingot: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Iron Ingot Fish" },
	goldingot: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Gold Ingot Fish" },
	copperingot: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Copper Ingot Fish" },
	deepslate: { realName: "Grimee", role: "Supports or No supports suggestions (depends on how useful)", category: "technicallyofficial", type: "mcblocks", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Deepslate Fish" },
	newcopper: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "New Copper Fish" },
	newercopper: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Newer Copper Fish" },
	newiron: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "New Iron Fish" },
	neweriron: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Newer Iron Fish" },
	newgolden: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "New Golden Fish" },
	newergolden: { category: "technicallyofficial", type: "mineral", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Newer Golden Fish" },
	
	glass: { realName: "Glasee", category: "technicallyofficial", type: "mcblocks", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Glass Fish" },
	bow: { realName: "Aimee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Bow Fish" },
	arrow: { realName: "Arrowee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Arrow Fish" },
	bowandarrow: { realName: "Aimee & Arrowee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Bow & Arrow Fish" },
	bucket: { realName: "Fillee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "LandonHarter", fullName: "Bucket Fish" },
	egg: { realName: "Yolkee", role: "Answers questions in QaS", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Egg Fish" },
	melon: { realName: "Melonee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Melon Fish" },
	mutton: { realName: "Ramee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Mutton Fish" },
	cookedmutton: { realName: "Ramsee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Cooked Mutton Fish" },
	paper: { realName: "Artee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: true, creator: "-gge", textureCreator: "-gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Paper Fish" },
	potato: { realName: "Spudee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Potato Fish" },
	slimeball: { realName: "Slimee", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Slimeball Fish" },
	chargedcreeper: { category: "technicallyofficial", type: "mcmobs", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Charged Creeper Fish" },
	chicken: { realName: "Bawkee", role: "Proposing articles to be featured", category: "technicallyofficial", type: "mcmobs", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Chicken Fish" },
	wheat: { realName: "Grainee", role: "Double quoting", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Wheat Fish" },
	cookie: { realName: "Pastree", category: "technicallyofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Cookie Fish" },
	prismarineshard: { category: "unofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Prismarine Shard Fish" },
	pig: { realName: "Oinkee", role: "Shops", category: "technicallyofficial", type: "mcmobs", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Pig Fish" },
	cow: { realName: "Bullee", role: "Scratch Wiki helper", category: "technicallyofficial", type: "mcmobs", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Cow Fish" },
	mooshroom: { realName: "Mooshee", role: "Proposing studios to be featured", category: "technicallyofficial", type: "mcmobs", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Mooshroom Fish" },
	air: { role: "Used in Mineral Fish pixel art", category: "technicallyofficial", type: "misc", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Air Fish" },
	
	
	flint: { realName: "Redundee", role: "Duplicate topics", category: "semiofficial", type: "mineral", bitmap: true, vector: true, creator: "Pianostar4", textureCreator: "-gge", fullName: "Flint Fish" },
	
	
	copper30: { category: "unofficial", type: "mineral", bitmap: true, vector: false, creator: "LandonHarter", textureCreator: "LandonHarter", fullName: "Copper Fish 3.0" },
	ruby: { category: "unofficial", type: "mineral", bitmap: true, vector: true, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", vectorTextureCreator: "LandonHarter", fullName: "Ruby Fish" },
	
	stone: { realName: "Soldee", role: "Rejected suggestions", category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "CST1229", textureCreator: "CST1229", fullName: "Stone Fish", vectorTextureCreator: "CST1229" },
	stone_old: { realName: "Soldee", role: "Rejected suggestions", category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "CST1229", textureCreator: "CST1229", fullName: "Stone Fish (Old sprite)", vectorTextureCreator: "CST1229" },
	stone_landon: { realName: "Soldee", role: "Rejected suggestions", category: "unofficial", type: "mcblocks", bitmap: false, vector: true, creator: "CST1229", fullName: "Stone Fish (LandonHarter's vector)" },
	jackolantern: { category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "Jack-O-Lantern Fish" },
	magma: { realName: "Mayami", role: "Deleting stuff", category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "-TWILIGHTMISTY-", textureCreator: "CST1229", fullName: "Magma (Block) Fish", vectorTextureCreator: "-TWILIGHTMISTY-" },
	beacon: { category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "-TWILIGHTMISTY-", textureCreator: "-gge", fullName: "Beacon Fish" },
	chest: { category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "-TWILIGHTMISTY-", textureCreator: "-gge", fullName: "Chest Fish" },
	endrod: { category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "End Rod Fish" },
	glowstone: { category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Glowstone Fish" },
	obsidian: { realName: "Portalee", role: "Large images", category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "TheGlassPenguin", textureCreator: "TheGlassPenguin", fullName: "Obsidian Fish" },
	skulk: { realName: "Bypee", role: "Filter bypassing", category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "irish-tea", textureCreator: "irish-tea", fullName: "Skulk Fish" },
	wool: { realName: "Woolee", role: "Manually inserted signatures", category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "TheGlassPenguin", textureCreator: "TheGlassPenguin", fullName: "Wool Fish" },
	clay: { category: "unofficial", type: "mcblocks", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Clay Fish" },
	commandite: { category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "LandonHarter", textureCreator: "LandonHarter", fullName: "Commandite Fish" },
	netherrack: { category: "unofficial", type: "mcblocks", bitmap: false, vector: true, creator: "LandonHarter", fullName: "Netherrack Fish" },
	purpur: { category: "unofficial", type: "mcblocks", bitmap: false, vector: true, creator: "LandonHarter", fullName: "Purpur Fish" },
	wooden: { role: "Telling people when something technically isn't a mineral fish", category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "PATSATDAT", textureCreator: "JackyBorderCollie", fullName: "Wooden Fish" },
	notfound: { realName: "Errorree", category: "unofficial", type: "mcblocks", bitmap: true, vector: false, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", fullName: "Not Found Fish" },
	
	
	apple: { realName: "Watchee", role: "Test topics", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", fullName: "Apple Fish" },
	bread: { role: "Unconstructive criticism", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "wkmewsic", textureCreator: "-gge", fullName: "Bread Fish" },
	ender: { realName: "Portee", role: "Topic moving", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", fullName: "Ender Fish" },
	phantommembrane: { realName: "Elitree", role: "Welcoming", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "roketH77", textureCreator: "-gge", fullName: "Phantom Membrane Fish" },
	cake: { realName: "Cakee", role: "Roleplaying in the forums", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "-TWILIGHTMISTY-", textureCreator: "-TWILIGHTMISTY-", fullName: "Cake Fish", vectorTextureCreator: "CST1229" },
	water: { role: "Helping Lapis Fish with flame wars", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "-TWILIGHTMISTY-", textureCreator: "-gge", vectorTextureCreator: "LandonHarter", fullName: "Water Fish" },
	lava: { role: "Turning Water Fish into stone", category: "unofficial", type: "mcitems", bitmap: false, vector: true, creator: "PATSATDAT", vectorTextureCreator: "LandonHarter", fullName: "Lava Fish" },
	fire: { role: "Causing flame wars", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "PATSATDAT", textureCreator: "JackyBorderCollie", fullName: "Fire Fish" },
	magmacream: { realName: "Magnee", role: "Topic merging", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "-TWILIGHTMISTY-", textureCreator: "-gge", fullName: "Magma (Cream) Fish" },
	dragonegg: { realName: "Revoltuzeë", role: "False reporting", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "Unithlees3", textureCreator: "-gge", fullName: "Dragon Egg Fish" },
	carrot: { category: "unofficial", role: "Multiple quoting", type: "mcitems", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Carrot Fish" },
	beetroot: { category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Beetroot Fish" },
	prismarinecrystal: { role: "Mass mentioning on the TBGs", category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "TonyBrown148", textureCreator: "TonyBrown148 & -gge", vectorTextureCreator: "JackyBorderCollie", fullName: "Prismarine Crystal Fish" },
	spyglass: { category: "unofficial", role: "Helps people in HwS", type: "mcitems", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "Spyglass Fish" },
	sweetberry: { category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Sweet Berry Fish" },
	firework: { category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Firework Fish" },
	chorus: { category: "unofficial", type: "mcitems", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Chorus Fish" },
	prismarineshard: { category: "unofficial", type: "mcitems", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Prismarine Shard Fish" },
	
	creeper: { category: "unofficial", type: "mcmobs", bitmap: true, vector: false, creator: "-TWILIGHTMISTY-", textureCreator: "-gge", fullName: "Creeper Fish" },
	enderman: { category: "unofficial", type: "mcmobs", bitmap: true, vector: false, creator: "TheGlassPenguin", textureCreator: "TheGlassPenguin", fullName: "Enderman Fish" },
	
	blorfstone: { category: "unofficial", type: "mcrandom", bitmap: true, vector: false, creator: "lapisi", textureCreator: "lapisi", fullName: "Blorfstone Fish" },
	ig: { category: "unofficial", type: "mcrandom", bitmap: true, vector: false, creator: "lapisi", textureCreator: "lapisi", fullName: "Ig Fish" },
	inzeozite: { category: "unofficial", type: "mcrandom", bitmap: true, vector: false, creator: "lapisi", textureCreator: "lapisi", fullName: "Inzeozite Fish" },
	
	firefighter: { category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "Marc92020", textureCreator: "-gge", vectorTextureCreator: "Marc92020", fullName: "Firefighter Fish" },
	grammarpolice: { role: "Grammar mistakes", category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "-TWILIGHTMISTY-", textureCreator: "-TWILIGHTMISTY-", fullName: "Grammar Police Fish" },
	banana: { realName: "Banee/Bananee", role: "Bullies, evil Scratchers", category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "Marc92020", textureCreator: "CST1229", vectorTextureCreator: "Marc92020", fullName: "Banana Fish" },
	ghost: { category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "54321Tigg", textureCreator: "Marc92020", vectorTextureCreator: "JackyBorderCollie", fullName: "Ghost Fish" },
	applerald: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "JackyBorderCollie's sister", textureCreator: "CST1229", fullName: "Applerald Fish" },
	micafish: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "CST1229", textureCreator: "CST1229", fullName: "Mica Fish Fish" },
	moonstone: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "-TWILIGHTMISTY-", textureCreator: "-TWILIGHTMISTY-", fullName: "Moonstone Fish" },
	blueberry: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", fullName: "Blueberry Fish" },
	tree: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "Marc92020", textureCreator: "Marc92020", fullName: "Tree Fish" },
	fullon: { category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "LandonHarter", vectorTextureCreator: "JackyBorderCollie", fullName: "Full On Fish" },
	cloud: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", vectorTextureCreator: "LandonHarter", fullName: "Cloud Fish" },
	daylight: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", vectorTextureCreator: "LandonHarter", fullName: "Daylight Fish" },
	moonlight: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", vectorTextureCreator: "LandonHarter", fullName: "Moonlight Fish" },
	galactic: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "Unithlees3", vectorTextureCreator: "LandonHarter", fullName: "Galactic Fish" },
	holo: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", vectorTextureCreator: "LandonHarter", fullName: "Holo Fish" },
	kumquat: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", vectorTextureCreator: "LandonHarter", fullName: "Kumquat Fish" },
	kumquatking: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", vectorTextureCreator: "LandonHarter", fullName: "Kumquat King Fish" },
	tempest: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", fullName: "Tempest Fish" },
	ticket: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "LandonHarter", fullName: "Ticket Fish" },
	alenn: { category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", vectorTextureCreator: "JackyBorderCollie", fullName: "Alenn Fish" },
	swimmy: { category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", vectorTextureCreator: "JackyBorderCollie", fullName: "Swimmy Fish" },
	brownie: { category: "unofficial", type: "misc", bitmap: false, vector: true, creator: "-TWILIGHTMISTY-", vectorTextureCreator: "LandonHarter (based off of -TWILILIGHTMISTY-'s vector)", fullName: "Brownie Fish" },
	rainbowstone: { category: "unofficial", type: "misc", bitmap: true, vector: true, creator: "lapisi", textureCreator: "-gge", fullName: "Rainbowstone Fish" },
	potassium: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "Scratchbeginner5669", textureCreator: "Scratchbeginner5669", fullName: "Potassium Fish" },
	liberachat: { role: "Unmoderated chat", realName: "Nopee, Cordlee, Redlee, Twerlee, Mailee, Cloudlee", category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "CST1229", textureCreator: "CST1229", fullName: "Libera Chat Fish" },
    	balloon: { category: "unofficial", realName: "Partyee", type: "misc", bitmap: true, vector: true, creator: "JackyBorderCollie's sister", textureCreator: "JackyBorderCollie", vectorTextureCreator: "JackyBorderCollie", fullName: "Balloon Fish" },
	ocular: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Ocular Fish" },
	ocularalt: { category: "unofficial", type: "misc", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Ocular Fish (Alt sprite)" },
	
	roket: { role: "Dealing with Mineral Fish haters", category: "unofficial", type: "oc", bitmap: true, vector: true, creator: "roketH77", textureCreator: "roketH77", vectorTextureCreator: "roketH77", fullName: "Roket Fish" },
	marc92020: { role: "Helping Roket Fish deal with Mineral Fish haters", category: "unofficial", type: "oc", bitmap: true, vector: true, creator: "-gge", textureCreator: "Marc92020", vectorTextureCreator: "-gge", fullName: "Marc92020 Fish" },
	cyruscarrasco15263: { category: "unofficial", type: "oc", bitmap: false, vector: true, creator: "-gge", vectorTextureCreator: "-gge", fullName: "CyrusCarrasco15263 Fish" },
	dog: { realName: "Jackyee", category: "unofficial", type: "oc", bitmap: false, vector: true, creator: "-gge", vectorTextureCreator: "-gge", fullName: "Jacky Fish" },
	gge: { category: "unofficial", type: "oc", bitmap: false, vector: true, creator: "-gge", vectorTextureCreator: "-gge", fullName: "-gge Fish" },
	scratchcat: { category: "unofficial", type: "oc", bitmap: false, vector: true, creator: "-gge", vectorTextureCreator: "-gge", fullName: "Scratch Cat Fish" },
	unithlees3: { category: "unofficial", type: "oc", bitmap: false, vector: true, creator: "-gge", vectorTextureCreator: "-gge", fullName: "Unithlees3 Fish" },
	twilight: { category: "unofficial", type: "oc", bitmap: false, vector: true, creator: "-TWILIGHTMISTY-", vectorTextureCreator: "-TWILIGHTMISTY-", fullName: "Twilight Fish" },
	redgreenandblue: { category: "unofficial", type: "oc", bitmap: true, vector: false, creator: "redgreenandblue", textureCreator: "redgreenandblue", fullName: "redgreenandfish" },
	
	hollow: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "-gge", textureCreator: "-gge", fullName: "Hollow Fish", smooth: true },
	sevcon: { category: "unofficial", type: "crossover", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Sevcon Fish" },
	lunartic: { category: "unofficial", type: "crossover", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "-gge", fullName: "Lunartic Fish" },
	orb: { realName: "Mutenee", role: "Conflict prevention", category: "unofficial", type: "crossover", bitmap: true, vector: true, creator: "LandonHarter", textureCreator: "LandonHarter", fullName: "Orb Fish" },
	orb_16x16: { realName: "Mutenee", role: "Conflict prevention", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "LandonHarter", textureCreator: "JackyBorderCollie", fullName: "Orb Fish (16x16 sprite)" },
	amogus: { realName: "Susee", role: "Sus things and impostor Mineral Fish", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "Among Fish" },
	among: { realName: "Susee", role: "Sus things and impostor Mineral Fish", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "Among Fish (Old sprite)", smooth: true },
	/* omg non-ascii character that is illegal /s */
	nausicaa: { category: "unofficial", type: "crossover", bitmap: true, vector: true, creator: "-TWILIGHTMISTY-", textureCreator: "-gge", fullName: "Nausicaä Fish" },
	babanana: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "LandonHarter", textureCreator: "LandonHarter", fullName: "Babanana Fish" },
	bapple: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "LandonHarter", textureCreator: "LandonHarter", fullName: "Bapple Fish" },
	hatsunemiku: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "Hatsune Miku Fish" },
	appel: { category: "unofficial", type: "crossover", bitmap: true, vector: true, creator: "CST1229", textureCreator: "CST1229", fullName: "Appel Fish", vectorTextureCreator: "CST1229" },
	camilo: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "Camilo Fish" },
	infinitygauntlet: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "-TWILIGHTMISTY-", textureCreator: "-TWILIGHTMISTY-", fullName: "Infinity Gauntlet Fish", smooth: true },
	nofish: { category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "roketH77", textureCreator: "roketH77", fullName: "No-fish" },
	olivee: { realName: "Olivee", role: "Good, making and editing pages on the Scratch/MF Wiki", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "gilbert_given_TBG", textureCreator: "gilbert_given_TBG", fullName: "Origami Fish" },
	ollee: { realName: "Ollee", role: "Evil, making and editing pages on the Scratch/MF Wiki", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "gilbert_given_TBG", textureCreator: "gilbert_given_TBG", fullName: "Origami Fish" },
	cube: { realName: "Dashee", role: "Rating Geometry Dash levels", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", fullName: "GD Cube Fish", },
	spike: { realName: "Crashee", role: "Making Geometry Dash levels harder", category: "unofficial", type: "crossover", bitmap: true, vector: false, creator: "JackyBorderCollie", textureCreator: "JackyBorderCollie", fullName: "GD Spike Fish", },
	
};
export function getString(str) {
	return strings[str] || str;
}
